---
title: "2_Figures"
author: "Maximilian Pichler"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
classif = readRDS("Results/classification.RDS")
regr = readRDS("Results/regression.RDS")
```

## Figure - 1 VENN 
```{r}
library(flextable)
classif_lm = apply(classif$classification[,2,],1,mean)
classif_lm_se = apply(classif$classification[,2,],1,sd)/sqrt(9)
names(classif_lm) = classif$names
classif_lm = data.frame(as.list(classif_lm))

regr_lm = apply(regr$regression[,2,],1,mean)
regr_lm_se = apply(regr$regression[,2,],1,sd)/sqrt(9)
names(regr_lm) = regr$names
regr_lm = data.frame(as.list(regr_lm))


classif_rf = apply(classif$classification[,1,],1,mean)
classif_rf_se = apply(classif$classification[,1,],1,sd)/sqrt(9)
names(classif_rf) = classif$names
classif_rf = data.frame(as.list(classif_rf))

regr_rf = apply(regr$regression[,1,],1,mean)
regr_rf_se = apply(regr$regression[,1,],1,sd)/sqrt(9)
names(regr_rf) = regr$names
regr_rf = data.frame(as.list(regr_rf))

p_values_classif = sapply(1:7, function(i) t.test(classif$classification[i,2,], classif$classification[i,1,])$p.value)
p_values_regr = sapply(1:7, function(i) t.test(regr$regression[i,2,], regr$regression[i,1,])$p.value)

classif_results = data.frame(round(cbind(t(classif_lm), classif_lm_se, t(classif_rf), classif_rf_se, p_values_classif), digits = 3))
regr_results = data.frame(round(cbind(t(regr_lm), regr_lm_se, t(regr_rf), regr_rf_se, p_values_regr), digits = 3))
colnames(classif_results) = colnames(regr_results) = c("lm", "lm-SE", "RF", "RF-SE", "p-value")
classif_results$Scenario = rownames(classif_results)
regr_results$Scenario = rownames(regr_results)
classif_results = classif_results[, c(6, 1:5)]
regr_results = regr_results[,c(6, 1:5)]
save_as_docx("Classification" = flextable(classif_results), "Regression" = flextable(regr_results), path = "Results/S1/2_tables.docx")



addA = function(col, alpha = 0.25) apply(sapply(col, grDevices::col2rgb)/255, 2, function(x) grDevices::rgb(x[1], x[2], x[3], alpha=alpha))
to_percent = function(number, ...) paste0(round(number, 3)*100, "%")


pdf(file = "Figures/Fig_1.pdf",width = 11, height = 10.1)
par(mfrow = c(2,2), mar = c(1, 2, 1, 2), oma = c(0.0, 0.5, 2.5, 0.5))

lineSeq = 0.3
nseg = 100
dr = 1.0
cols = RColorBrewer::brewer.pal(3, "Dark2")
alpha=0.20

#### RF
graphics::plot(NULL, NULL, xlim = c(0,1), ylim =c(0,1),pty="s", axes = FALSE, xlab = "", ylab = "")
text(-0.06, 1.1, labels = "A", font = 2, xpd=NA, pos = 1, cex = 1.3)
text(0.5, 1.13, labels = "PA of seed bank", font = 2, xpd=NA, pos = 1, cex = 1.3)
xx = 1.1*lineSeq*cos( seq(0,2*pi, length.out=nseg))
yy = 1.1*lineSeq*sin( seq(0,2*pi, length.out=nseg))
graphics::polygon(xx+lineSeq,yy+(1-lineSeq), col= addA(cols[1],alpha = alpha), border = cols[1], lty = 1, lwd = 2.2)
graphics::text(lineSeq-0.1, (1-lineSeq),labels = to_percent(classif_rf$Env, 3))
graphics::text(mean(xx+lineSeq), 0.9,labels = "Environment", pos = 3) #A

graphics::polygon(xx+1-lineSeq,yy+1-lineSeq, col= addA(cols[2],alpha = alpha), border = cols[2], lty = 1, lwd = 2.2)
graphics::text(1-lineSeq+0.1, (1-lineSeq),labels = to_percent(classif_rf$Phylo, 3))
graphics::text(1-mean(xx+lineSeq), 0.9,labels = "Phylogeny", pos = 3) #B
graphics::text(0.5, (1-lineSeq),labels = to_percent(classif_rf$Phylo.Env, 3))
  
graphics::polygon(xx+0.5,yy+lineSeq, col= addA(cols[3],alpha = alpha), border = cols[3], lty = 1, lwd = 2.2)
graphics::text(0.5, lineSeq+0.0,pos = 1,labels = to_percent(classif_rf$Seed, 3))
graphics::text(0.5, 0.1,labels = "Seed Traits", pos = 1) # C
graphics::text(0.3, 0.5,pos=1,labels = to_percent(classif_rf$Env.Seed, 3)) #A+C
graphics::text(1-0.3, 0.5,pos=1,labels = to_percent(classif_rf$Phlyo.Seed, 3))
graphics::text(0.5, 0.5+0.05,labels = to_percent(classif_rf$All, 3))

### B
graphics::plot(NULL, NULL, xlim = c(0,1), ylim =c(0,1),pty="s", axes = FALSE, xlab = "", ylab = "")
text(0.5, 1.13, labels = "Density of seed bank", font = 2, xpd=NA, pos = 1, cex = 1.3)
xx = 1.1*lineSeq*cos( seq(0,2*pi, length.out=nseg))
yy = 1.1*lineSeq*sin( seq(0,2*pi, length.out=nseg))
graphics::polygon(xx+lineSeq,yy+(1-lineSeq), col= addA(cols[1],alpha = alpha), border = cols[1], lty = 1, lwd = 2.2)
graphics::text(lineSeq-0.1, (1-lineSeq),labels = to_percent(regr_rf$Env, 3))
graphics::text(mean(xx+lineSeq), 0.9,labels = "Environment", pos = 3) #A

graphics::polygon(xx+1-lineSeq,yy+1-lineSeq, col= addA(cols[2],alpha = alpha), border = cols[2], lty = 1, lwd = 2.2)
graphics::text(1-lineSeq+0.1, (1-lineSeq),labels = to_percent(regr_rf$Phylo, 3))
graphics::text(1-mean(xx+lineSeq), 0.9,labels = "Phylogeny", pos = 3) #B
graphics::text(0.5, (1-lineSeq),labels = to_percent(regr_rf$Phylo.Env, 3))
  
graphics::polygon(xx+0.5,yy+lineSeq, col= addA(cols[3],alpha = alpha), border = cols[3], lty = 1, lwd = 2.2)
graphics::text(0.5, lineSeq+0.0,pos = 1,labels = to_percent(regr_rf$Seed, 3))
graphics::text(0.5, 0.1,labels = "Seed Traits", pos = 1) # C
graphics::text(0.3, 0.5,pos=1,labels = to_percent(regr_rf$Env.Seed, 3)) #A+C
graphics::text(1-0.3, 0.5,pos=1,labels = to_percent(regr_rf$Phlyo.Seed , 3))
graphics::text(0.5, 0.5+0.05,labels = to_percent(regr_rf$All, 3))

#### LM
### A
graphics::plot(NULL, NULL, xlim = c(0,1), ylim =c(0,1),pty="s", axes = FALSE, xlab = "", ylab = "")
text(-0.06, 1.1, labels = "B", font = 2, xpd=NA, pos = 1, cex = 1.3)
xx = 1.1*lineSeq*cos( seq(0,2*pi, length.out=nseg))
yy = 1.1*lineSeq*sin( seq(0,2*pi, length.out=nseg))
graphics::polygon(xx+lineSeq,yy+(1-lineSeq), col= addA(cols[1],alpha = alpha), border = cols[1], lty = 1, lwd = 2.2)
graphics::text(lineSeq-0.1, (1-lineSeq),labels = to_percent(classif_lm$Env, 3))
graphics::text(mean(xx+lineSeq), 0.9,labels = "Environment", pos = 3) #A

graphics::polygon(xx+1-lineSeq,yy+1-lineSeq, col= addA(cols[2],alpha = alpha), border = cols[2], lty = 1, lwd = 2.2)
graphics::text(1-lineSeq+0.1, (1-lineSeq),labels = to_percent(classif_lm$Phylo, 3))
graphics::text(1-mean(xx+lineSeq), 0.9,labels = "Phylogeny", pos = 3) #B
graphics::text(0.5, (1-lineSeq),labels = to_percent(classif_lm$Phylo.Env, 3))
  
graphics::polygon(xx+0.5,yy+lineSeq, col= addA(cols[3],alpha = alpha), border = cols[3], lty = 1, lwd = 2.2)
graphics::text(0.5, lineSeq+0.0,pos = 1,labels = to_percent(classif_lm$Seed, 3))
graphics::text(0.5, 0.1,labels = "Seed Traits", pos = 1) # C
graphics::text(0.3, 0.5,pos=1,labels = to_percent(classif_lm$Env.Seed, 3)) #A+C
graphics::text(1-0.3, 0.5,pos=1,labels = to_percent(classif_lm$Phlyo.Seed, 3))
graphics::text(0.5, 0.5+0.05,labels = to_percent(classif_lm$All, 3))

### B
graphics::plot(NULL, NULL, xlim = c(0,1), ylim =c(0,1),pty="s", axes = FALSE, xlab = "", ylab = "")
#text(-0.06, 1.1, labels = "B", font = 2, xpd=NA, pos = 1, cex = 1.3)
xx = 1.1*lineSeq*cos( seq(0,2*pi, length.out=nseg))
yy = 1.1*lineSeq*sin( seq(0,2*pi, length.out=nseg))
graphics::polygon(xx+lineSeq,yy+(1-lineSeq), col= addA(cols[1],alpha = alpha), border = cols[1], lty = 1, lwd = 2.2)
graphics::text(lineSeq-0.1, (1-lineSeq),labels = to_percent(regr_lm$Env, 3))
graphics::text(mean(xx+lineSeq), 0.9,labels = "Environment", pos = 3) #A

graphics::polygon(xx+1-lineSeq,yy+1-lineSeq, col= addA(cols[2],alpha = alpha), border = cols[2], lty = 1, lwd = 2.2)
graphics::text(1-lineSeq+0.1, (1-lineSeq),labels = to_percent(regr_lm$Phylo, 3))
graphics::text(1-mean(xx+lineSeq), 0.9,labels = "Phylogeny", pos = 3) #B
graphics::text(0.5, (1-lineSeq),labels = to_percent(regr_lm$Phylo.Env, 3))
  
graphics::polygon(xx+0.5,yy+lineSeq, col= addA(cols[3],alpha = alpha), border = cols[3], lty = 1, lwd = 2.2)
graphics::text(0.5, lineSeq+0.0,pos = 1,labels = to_percent(regr_lm$Seed, 3))
graphics::text(0.5, 0.1,labels = "Seed Traits", pos = 1) # C
graphics::text(0.3, 0.5,pos=1,labels = to_percent(regr_lm$Env.Seed, 3)) #A+C
graphics::text(1-0.3, 0.5,pos=1,labels = to_percent(regr_lm$Phlyo.Seed , 3))
graphics::text(0.5, 0.5+0.05,labels = to_percent(regr_lm$All, 3))

dev.off()

```


## Figure - 2 Cumulative predictive performance
```{r}
cols = RColorBrewer::brewer.pal(3, "Dark2")

pdf(file = "Figures/Fig_2.pdf",width = 14, height = 6.1)

par(mfrow = c(1,2), mar = c(3,4,1,1), oma = rep(1, 4))

## A
classif_cumulative = apply(classif$cumulative$results,1, mean)
names(classif_cumulative) = classif$cumulative$names
classif_cumulative = data.frame(as.list(classif_cumulative))

values = c(0.5, unlist(classif_cumulative[1,1:4]))
x_seq = c(0.0, 0.25, 0.5, 0.75, 1.0)
plot(NULL, NULL, xlim = c(0,1), ylim = c(0.5,1), las = 1, xaxt= "n", ylab = "AUC")
text(x = -0.14, y = 1.04, labels = "A", font = 2, xpd = NA, cex = 1.3)
text(x = 0.5, y = 0.45, pos = 1, labels = "Predictors", xpd = NA)
abline(h = apply(classif$classification[,1,], 1, mean)[1], lty = 3)
legend("topright", legend = "All predictors", lty = 3, bty = "n")

predictors = names(classif_cumulative)[1:4]
predictors[which(predictors == "T")] = "Temperature"
predictors[which(predictors == "Cover")] = "Vegetation"
predictors[which(predictors == "Weight")] = "Mass"
for(i in 1:4){
  arrows(x_seq[i], y0 = values[i], y1 = values[i+1], lty = 1, length = 0.15, col = cols[1], lwd = 2.5)
  
  segments(y0 = values[i+1], x0 =  x_seq[i], x1 =  x_seq[i+1], lwd = 2)
  text(x = x_seq[i]+0.03, y = values[i]+(values[i+1] - values[i])/2, pos = 4, 
      labels = paste0("+", round(values[i+1] - values[i], 3)*100, "%"),
      col = cols[1])
  
  for(j in 1:i){
    if(i == j ) {
      aa = 1.0
      add = "+"
    } else {
      aa = 0.3
      add = " "
    }
      text(x = x_seq[i]+0.03, y = seq(0.5, to = 0.6, length.out = 4)[j], pos = 4, 
      labels = paste0(add, predictors[j]), col = addA("black", aa ))
  }
}


## B
regr_cumulative = apply(regr$cumulative$results,1, mean)
names(regr_cumulative) = regr$cumulative$names
regr_cumulative = data.frame(as.list(regr_cumulative))

values = c(0.0, unlist(regr_cumulative[1,1:4]))
x_seq = c(0.0, 0.25, 0.5, 0.75, 1.0)
plot(NULL, NULL, xlim = c(0,1), ylim = c(0.0,1), las = 1, xaxt= "n", ylab = "R2", xlab = "Predictors" )
text(x = -0.14, y = 1.08, labels = "B", font = 2, xpd = NA, cex = 1.3)
legend("topright", legend = "All predictors", lty = 3, bty = "n")
abline(h = apply(regr$regression[,1,], 1, mean)[1], lty = 3)
text(x = 0.5, y = -0.1, pos = 1, labels = "Predictors", xpd = NA)

predictors = names(regr_cumulative)[1:4]
predictors[which(predictors == "T")] = "Temperature"
predictors[which(predictors == "Cover")] = "Vegetation"
predictors[which(predictors == "Weight")] = "Mass"
for(i in 1:4){
  arrows(x_seq[i], y0 = values[i], y1 = values[i+1], lty = 1, length = 0.15, col = cols[1], lwd = 2.5)
  
  segments(y0 = values[i+1], x0 =  x_seq[i], x1 =  x_seq[i+1], lwd = 2)
  text(x = x_seq[i]+0.03, y = values[i]+(values[i+1] - values[i])/2, pos = 4, 
      labels = paste0("+", round(values[i+1] - values[i], 3)*100, "%"),
      col = cols[1])
  
  for(j in 1:i){
    if(i == j ) {
      aa = 1.0
      add = "+"
    } else {
      aa = 0.3
      add = " "
    }
      text(x = x_seq[i]+0.03, y = seq(0.0, to = 0.2, length.out = 4)[j], pos = 4, 
      labels = paste0(add, predictors[j]), col = addA("black", aa ))
  }
}

dev.off()


```


## Figure - 3 Importance
```{r}
cols = addA(RColorBrewer::brewer.pal(3, "Dark2"), 0.5)
# Env Phylo Seed
seed=  c("Endosperm", "Weight", "Shape", "Productivity", "Dormancy")
env =  c("T", "F", "N", "Grazing", "Cover")
pyhlogenetic = names(classif$rf$model$variable.importance)[grep( "c+[0-9]+",names(classif$rf$model$variable.importance))]



which_col = function(n)  {
  if(n %in% env){ return(cols[1]) }
  else if(n %in% pyhlogenetic) { return(cols[2]) } 
  else { return(cols[[3]])}
}

cols_class = sapply(names(classif$rf$model$variable.importance), which_col)
cols_reg = sapply(names(regr$rf$model$variable.importance), which_col)

imp_classif = classif$rf$model$variable.importance
imp_regr = regr$rf$model$variable.importance
pdf("Figures/Fig_3.pdf", width = 7.7, height = 7.7)
par(mfrow = c(2, 1), mar = c(5,5, 1, 1), oma = rep(1,4))

names = names(sort(imp_classif, decreasing = TRUE))
names[which(names == "Cover", arr.ind = TRUE)] = "Vegetation"
names[which(names == "Weight", arr.ind = TRUE)] = "Mass"
names[which(names == "Productivity", arr.ind = TRUE)] = "Production"
barplot(sort(imp_classif, decreasing = TRUE)/sum(imp_classif), las = 2, col = cols_class[order(imp_classif, decreasing = TRUE)], ylab = "Importance (Gini index) in %", names.arg = names)

text(-4, 0.09, labels = "A", xpd = NA, font = 2, cex = 1.3)
legend("topright", bty = "n", legend = c("Environment","Phylogeny", "Seed"), col = cols , pch = 15)

names = names(sort(imp_regr, decreasing = TRUE))
names[which(names == "Cover", arr.ind = TRUE)] = "Vegetation"
names[which(names == "Weight", arr.ind = TRUE)] = "Mass"
names[which(names == "Productivity", arr.ind = TRUE)] = "Production"
barplot(sort(imp_regr, decreasing = TRUE)/sum(imp_regr), las = 2, col = cols_reg[order(imp_classif, decreasing = TRUE)], ylab = "Importance (Gini index) in %", names.arg = names)
text(-4, 0.09, labels = "B", xpd = NA, font = 2, cex = 1.3)


dev.off()
```




## Figure - 4 xAI 
```{r}
library(mlr3)
library(DALEX)
library(ingredients)
set.seed(42)
complete_scaled = readRDS("Results/cleaned_data.RDS")
reference = readRDS("Results/reference_data.RDS")
#### Model diagnostic Classification



# Classif
which_SBPA = which(colnames(complete_scaled) == "SBPA", arr.ind = TRUE)
explainer = function(object, newdata){
  preds = object$predict_newdata(newdata=newdata)
  return(preds$data$prob[,1])
}
model_explainer_rf_classif = DALEX::explain(classif$rf, 
                                    data=complete_scaled[reference$dataset=="train",c(-which_SBPA)], 
                                    y=as.integer(complete_scaled[reference$dataset=="train",which_SBPA])-1L,
                                    predict_function = explainer, label = "RF")
dp_classif = conditional_dependence(model_explainer_rf_classif, 
                            grid_points = 500, 
                            #variable_splits_type="uniform",
                            )

dp_classif = as.data.frame(dp_classif)
colnames(dp_classif) = c( "vname", "label", "x", "yhat", "id")

# Regr
which_SBDensity= which(colnames(complete_scaled) == "SBDensity", arr.ind = TRUE)
explainer = function(object, newdata){
  preds = object$predict_newdata(newdata=newdata)
  return(exp(preds$data$response) - 0.001)
}
model_explainer_rf_regr= DALEX::explain(regr$rf, 
                                    data=complete_scaled[reference$dataset=="train",c(-which_SBDensity)], 
                                    y=exp(complete_scaled[reference$dataset=="train",which_SBDensity]) - 0.01,
                                    predict_function = explainer, label = "RF")
dp_regr = conditional_dependence(model_explainer_rf_regr, 
                                grid_points = 500, 
                                variable_splits_type="uniform")

dp_regr = as.data.frame(dp_regr)
colnames(dp_regr) = c( "vname", "label", "x", "yhat", "id")
dp_regr



```



```{r}

plot_dependence = function(sub, ylim = c(0.0, 1.0), spar = 0.3, col = "grey", new = TRUE) {
  xlim = c(0.0, 1.0)
  X = scales::rescale(sub$x, to = c(0, 1))
  if(new) plot(NULL, NULL, axes = TRUE, xlim = xlim, ylim =ylim, yaxt = "n", xlab = "", ylab = "", xaxt="n")
  spline = smooth.spline(x =X, y = sub$yhat, spar = spar)
  lines(spline, lwd = 1.5, col = col)
}

plot_axis = function(w, mgp = c(3, 2, 0)) {
    
  pred = predict(lm(raw~scaled, data=data.frame(raw=reference[[w]], scaled=complete_scaled[[w]])), 
                   newdata=data.frame(scaled=dp_classif[dp_classif$vname==w,]$x))
  
  if(max(pred) > 1e5) digits = -4
  else digits = 1
  axis(1, 
       labels = (format(round(seq(min(pred), max(pred), length.out = 3), digits = digits), 
                        digits =2, nsmall = 1)),
       at= seq(0, 1.0, length.out = 3), mgp =mgp)
  
}

pdf("Figures/Fig_4.pdf", width = 10.0, height = 3.5)
spar =  0.9
ylim = c(0.1, 0.4)
xlim = c(0.0, 1.0)
par(mfrow = c(2, 7), mar = c(1, 0.15, 0.2, 0.15)+0.2, oma = c(4, 5, 2, 2))
cex = 1.5
counter = 1
mains = c("Landolt' T", "Seed shape", "Seed mass", "Landolt' F", "Grazing", "Landolt' N", "Production")
for(n in c("T", "Shape", "Weight", "F", "Grazing", "N", "Productivity")) {
  plot_dependence(dp_classif[dp_classif$vname==n,], ylim = ylim, spar = 0.0, col = "grey")
  plot_dependence(dp_classif[dp_classif$vname==n,], ylim = ylim, spar = 0.9, col = "black", new = FALSE)
  if(n == "T") {
    axis(side = 2, at = seq(0.1, 0.4, length.out = 4), labels = seq(0.1, 0.4, length.out = 4), xpd = NA, las = 1)
    text(srt = 90, x = -0.37, y = 0.25, pos = 3, labels = "PA of SSB", xpd= NA, cex = cex)
  }
  text(x=0.01, pos = 3, y = 0.366, labels = LETTERS[counter], font =2)
  text(x = 0.5, pos = 3, y = 0.41, xpd = NA, labels = mains[counter], cex = cex)
  counter = counter + 1
}

ylim = c(0.0, 130.0)
mgp = c(3, 1, 0)
for(n in c("T", "Shape", "Weight", "F", "Grazing", "N", "Productivity")) {
  plot_dependence(dp_regr[dp_regr$vname==n,], ylim = ylim, spar = 0.0, col = "grey")
  plot_dependence(dp_regr[dp_regr$vname==n,], ylim = ylim, spar = 0.9, col = "black", new = FALSE)
  plot_axis(n, mgp = mgp)
  if(counter %% 2 == 0) mgp = c(3, 2, 0)
  else mgp = c(3, 1, 0)
  if(n == "T") {
    axis(side = 2, at = seq(0.0, 130, length.out = 6), labels = seq(0.0, 130, length.out = 6), xpd = NA, las = 1)
    text(srt = 90, x = -0.37, y = 60, pos = 3, labels = "SSB Density", xpd= NA, cex = cex)
  }
  text(x=0.01, pos = 3, y = 115.95, labels = LETTERS[counter], font = 2)
  counter = counter + 1
  if(n == "F") text(x = 0.5, y = -70, xpd = NA, labels = "Predictor values", cex = cex)
}

dev.off()

```

## Figure - S1 Correlation
```{r}
library(corrplot)
data = complete_scaled[,-c(1,2)]
names = colnames(data)
colnames(data)[which(names == "Cover", arr.ind = TRUE)] = "Vegetation"
colnames(data)[which(names == "Weight", arr.ind = TRUE)] = "Mass"

pdf("Figures/Fig_S1.pdf", width = 7, height = 8)

par(mfrow = c(1,1))
corrplot(cor(data), type="upper")
dev.off()
```

## Figure - S2 Effect sizes
```{r}
library(glmnet)
pdf("Figures/Fig_S2.pdf", width = 9, height = 8)
par(mfrow = c(2, 1), oma = c(5, 2, 2, 2))
classification = readRDS("Results/classification.RDS")
model = classification$lm$model$classif.cv_glmnet$model
tmp_coeffs = coef(model, s = "lambda.min")
effects = data.frame(name = tmp_coeffs@Dimnames[[1]][tmp_coeffs@i + 1], 
                     coefficient = tmp_coeffs@x)
sub = effects[order(abs(effects$coefficient), decreasing = TRUE),][1:30,]
bars = sub$coefficient
names(bars) = sub$name
barplot(abs(bars), las = 2)
text(-2, 1.2, label = "A", font = 2, xpd = NA)

regression = readRDS("Results/regression.RDS")
model = regression$lm$model$regr.cv_glmnet$model
tmp_coeffs = coef(model, s = "lambda.min")
effects = data.frame(name = tmp_coeffs@Dimnames[[1]][tmp_coeffs@i + 1], 
                     coefficient = tmp_coeffs@x)
sub = effects[order(abs(effects$coefficient), decreasing = TRUE),][1:30,]
bars = sub$coefficient
names(bars) = sub$name
barplot(abs(bars), las = 2)
text(-2, 4, label = "B", font = 2, xpd = NA)

dev.off()
```

